<xs:schema xmlns="http://www.rixg.org.uk/" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.rixg.org.uk/">
    <xs:complexType name="CF_EDTA_PRD">
        <!-- Also known as RR4/RR20 -->
        <xs:sequence>
            <xs:element name="CodingStandard" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="EDTA"/>
                        <xs:enumeration value="EDTA2"/>
                        <xs:enumeration value="SNOMED"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Code" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>
                        Code values for PRD are maintained in the Registry Codes repository https://github.com/renalreg/registry-codes:
                        - tables/code_list/edta_prd.csv
                        - tables/code_list/edta2.csv
                        - tables/code_list/snomed_renal_diagnosis.csv
                
                        Any valid SNOMED CT code may be submitted when CodingStandard = SNOMED.
                    </xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="18"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Description" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="255"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
