name: Release Wheel

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel pyxb

      - name: Build schemas
        run: |
          pyxbgen -m schema_build/ukrdc_schema/pv_2_0_schema -u "file:////${PWD}/schema/pv2/PV_2_0.xsd"
          pyxbgen -m schema_build/ukrdc_schema/ukrdc_schema -u "file:////${PWD}/schema/ukrdc/UKRDC.xsd"
          pyxbgen -m schema_build/ukrdc_schema/rrtf_schema -u "file:////${PWD}/schema/rrtf/RRTF_4.xsd"
          cd schema_build
          python setup.py bdist_wheel

      - uses: actions/upload-artifact@v2
        with:
          name: ukrdc_schema_wheel
          path: schema_build/dist/*.whl

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: schema_build/dist/*.whl
