name: Test and Publish Schema Libraries

on:
  push:

jobs:
  build-pyxb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel pyxb

      - name: Build PyXB models
        run: |
          pyxbgen -m pyxb_build/ukrdc_schema/pv_2_0_schema -u "file:////${PWD}/schema/pv2/PV_2_0.xsd"
          pyxbgen -m pyxb_build/ukrdc_schema/ukrdc_schema -u "file:////${PWD}/schema/ukrdc/UKRDC.xsd"
          pyxbgen -m pyxb_build/ukrdc_schema/rrtf_schema -u "file:////${PWD}/schema/rrtf/RRTF_4.xsd"
          cd pyxb_build
          python setup.py bdist_wheel

      - uses: actions/upload-artifact@v4
        with:
          name: ukrdc_schema_wheel
          path: pyxb_build/dist/*.whl

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN_SCHEMA }}
          packages_dir: pyxb_build/dist


  build-xsdata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel xsdata[cli,lxml,soap]

      - name: Build XSData models
        run: |
          cd xsdata_build
          ./build.sh
          python setup.py bdist_wheel

      - uses: actions/upload-artifact@v4
        with:
          name: ukrdc_xsdata_wheel
          path: xsdata_build/dist/*.whl

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN_XSDATA }}
          packages_dir: xsdata_build/dist

  github-release:
    runs-on: ubuntu-latest
    needs: [build-pyxb, build-xsdata]

    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/download-artifact@v2

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./**/*.whl
