name: Validate Sample Files

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: sudo apt install libxml2-utils

      - name: Validate UKRDC sample files
        env:
          SAMPLE_BASE: ./sample_files/ukrdc
          SCHEMA: ./schema/ukrdc/UKRDC.xsd
        run: for in_file in $SAMPLE_BASE/*.xml; do xmllint --schema "$SCHEMA" "$in_file" --noout; done
